sudo: required
services:
    - docker

before_install:
    - docker build -t arunjoney994/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arunjoney994/react-test npm run test -- --coverage

after_success:
    - docker build -t arunjoney994/multi-client ./client
    - docker build -t arunjoney994/multi-nginx ./nginx
    - docker build -t arunjoney994/multi-server ./server
    - docker build -t arunjoney994/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push arunjoney994/multi-client
    - docker push arunjoney994/multi-nginx
    - docker push arunjoney994/multi-server
    - docker push arunjoney994/multi-worker